name: example
description: Example for package MagicDraw.
homepage: https://github.com/signmotion/magic_draw
publish_to: none

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_helpers:
    path: ../../dart_helpers
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  magic_draw:
    path: ../../magic_draw

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/spheres/
