name: magic_draw
description: >-
  A widget for custom canvas with animated magic effects.
  Feel free to use it in your projects.
repository: https://github.com/signmotion/title
publish_to: none
topics:
  - canvas
  - magic
  - effects
  - custom
  - widget

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc_concurrency: ^0.2.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  path_animation: ^1.0.3

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
